### ISSUE TITLE
pixel illustration for the front page

### ISSUE THREAD

**Issue by jimmac** [fleet-commander/fleet-commander.github.io#10]
Just like toolbox and pipewire, fleet commander deserves a nice eye-catching illustration for the front page.

**Comment by olivergs** [comment]
I did not expect less from you :)

**Comment by jimmac** [comment]
Initial idea:

![Fleet_Commander](https://user-images.githubusercontent.com/14821/135282687-14bbe8cb-f3a8-42b9-9aad-96fecbed5191.png)

**Comment by aruiz** [comment]
I like where this is going

**Comment by jimmac** [comment]
It's getting a little heavy in pixel execution, maybe tone down the detail a little.

![Fleet Commander](https://user-images.githubusercontent.com/14821/135305891-d6e2266c-92d0-4061-8cfc-57ea7b2cc001.png)

**Comment by jimmac** [comment]
With some increased lighness of the foreground, it could work.

![Fleet Commander](https://user-images.githubusercontent.com/14821/135342259-8c6ff65a-ab9f-4303-9f16-8c2cb9a7bcaa.gif)

**Comment by olivergs** [comment]
I absolutely love it.

Cats will dominate the world with Fleet Commander.

**Comment by jimmac** [comment]
You just need to get the cat out of the cockpit.
