### ISSUE TITLE
Minor phrasing change on project landing page

### ISSUE THREAD

**Issue by j1mc** [fleet-commander/fleet-commander.github.io#3]
It appears as though this github repo only includes the middleman-generated html, and that I don't have access to the sources, but there appears to be gendered language in the landing page. The phrase is here:
`By using a virtual machine, the admin can fine tune the configuration for a profile in real time and get an overview of the changes **he** made at the end of the process`. This assumes that the admin is a man.

I think it could be changed to: `By using a virtual machine, the admin can fine tune the configuration for a profile in real time and get an overview of the changes they made at the end of the process` or `By using a virtual machine, the admin can fine tune the configuration for a profile in real time and get an overview of the changes that are made at the end of the process.`

Thanks for your consideration.

**Comment by olivergs** [comment]
Thanks @j1mc for pointing this error. Our intention was not to gender the information, but probably due to the fact that my native language is Spanish and in Spanish the neutral form is the male form, maybe I did that mistake.

Fixing it ASAP.

**Comment by olivergs** [comment]
Ah! I forgot to mention the middleman code is in the sources branch :)

**Comment by j1mc** [comment]
Thanks so much! I didn't think it was intentional, and the writing is very well done, so kudos for writing this up so well in a non-native language. And thanks for your efforts on this project.  :+1:
